### ISSUE TITLE
Beginner friendly ML from scratch

### ISSUE THREAD

**Issue by Anindyadeep** [microsoft/ML-For-Beginners#501]
Hello, as mentioned earlier, I will be covering these following topics:

**(Level 0) Basic Mathematical Tools required for ML**
This section includes

1. Basic Linear algebra Concepts like vectors, matrix, tensors (little bit), some basic operations of matrices, and vectors like dot products, matrix multiplications. Also some code examples of numpy operations of the above concepts and operations required frequently.
2. Some basics of probability, like conditionals, Bayes Theorem, etc. 
3. Very basics of differentiation. 

**(Level 1) Supervised ML algorithm**
This section includes

1. Introduction to simple linear regression.
2. Using those earlier concepts, I will break down the concept of simple linear regression into several parts, and step by step code our own regression algorithm from scratch (using numpy only).
3. Once done, we will compare the results with sklearn, using one dummy datasets.

**(Level 2) Logistic regression**
This section includes

1. Classification is another important aspect of supervised learning. And I am not including that in the previous level (just to not make it overwhelming) 
2. We will cover the basics of logistic regression, and similar to the previous level, we will code it from scratch (for both binary and multi class classification) 
3. And finally, we will compare that with sklearn. 

**(Level 3) Unsupervised ML algorithm**
Here we will include just one algorithm, to keep this total curriculum short, and simple. So this section includes:

1. Understanding K-means clustering, its theory.
2. Like the previous sections, here also we will break the concepts and cover those one by one.
3. Finally making our own algorithm using numpy.

Please review this curriculum, I thought of. I will also provide good resources for further studies. Also I will do my very best to keep things, as simple as possible. Also please check out this [colab](https://colab.research.google.com/drive/1vwwsYIWGyyz8O_HxfxscRX49Wfh18Q9Z?usp=sharing), This is just for demo purpose. I generally use latex for important equations. And also, I use my own hand drawn images for graphics. If all these seems fine, then please let me know. Thank you.

**Comment by jlooper** [comment]
Hello,

Please remember, per my previous email, that since most of what you have mentioned in this curriculum are topics we have already covered, we are only interested in considering the addition of ONE sidecar lesson on math for ML (your first topic). 

The style should match our written style, which your colab does not so far. Statements such as "Here I am assuming that the readers at least know the very fundamentals of calculus" are not inline with our style guide. I will be the one who will create the illustrations, so that part is not necessary.

A lesson template is here: https://github.com/microsoft/Web-Dev-For-Beginners/tree/main/lesson-template and our style guide is here: https://github.com/jlooper/curriculum-template/wiki

Please provide a detailed outline of the ONE sidecar lesson you intend to provide, making sure that it follows our format. I don't want to guarantee that this submission will be included in this curriculum, since as I said, the topics are fixed and completed, but I'm open to reviewing an outline as a first step of many.

thank you!

**Comment by Anindyadeep** [comment]
Thank you, for giving me a chance. I will do my best and follow according to the template provided.
